Repository voxpupuli/puppet_webhook, pull requests merged in 2018-04, with the labels that each got.

#47 Clarify that mco is not a hard requirement
  README.md
  puppet_webhook.gemspec
Labels: in progress

#48 Release 1.2.0
  CHANGELOG.md
  puppet_webhook.gemspec
Labels: skip-changelog

#50 Add additional Slack options.
  lib/helpers/tasks.rb
  lib/puppet_webhook.rb
Labels: enhancement

#49 Async routes
  lib/helpers/tasks.rb
  lib/routes/module.rb
  lib/routes/payload.rb
Labels: enhancement

#51 Release 1.3.0
  CHANGELOG.md
  README.md
  puppet_webhook.gemspec
Labels: in progress, skip-changelog
