Repository voxpupuli/puppet_webhook, pull requests merged in 2019-02, with the labels that each got.

#88 Fix a http body param bug
  .gitignore
  Gemfile.lock
  app/controllers/api/v1/r10k/environment_controller.rb
Labels: bug

#92 Release 1.7.0
  CHANGELOG.md
  Rakefile
  puppet_webhook.gemspec
Labels: skip-changelog

#93 Remove gemnasium badge
  README.md
Labels: docs
