Repository voxpupuli/puppet_webhook, pull requests merged in 2020-07, with the labels that each got.

#135 Bugfix: Run Puma in production mode
  resources/puppetwebhook
Labels: bug

#137 Fix a parser issue with the module endpoint
  app/controllers/api/v1/r10k/environment_controller.rb
  app/controllers/api/v1/r10k/module_controller.rb
  app/controllers/application_controller.rb
Labels: bug

#138 document webhook configuration
  README.md
  images/gh.png
Labels: docs

#139 Release 2.1.2
  CHANGELOG.md
  lib/puppet_webhook.rb
Labels: skip-changelog
